# Generated by Django 5.1.1 on 2024-09-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=1000)),
                ('work_exp', models.TextField(max_length=1000, null=True)),
                ('about_you', models.TextField(max_length=1000)),
            ],
        ),
    ]
